module.exports = {
  "@typescript-eslint/indent": ["error", 4],
  "@typescript-eslint/member-delimiter-style": ["off"],
  "@typescript-eslint/explicit-function-return-type": ["off"],
  "@typescript-eslint/prefer-interface": ["off"],
  "@typescript-eslint/adjacent-overload-signatures": ["error"],
  "@typescript-eslint/ban-ts-ignore": ["error"],
  "@typescript-eslint/ban-types": ["error"],
  "@typescript-eslint/camelcase": ["error"],
  "@typescript-eslint/class-name-casing": ["error"],
  "@typescript-eslint/consistent-type-assertions": ["error"],
  "@typescript-eslint/interface-name-prefix": ["error"],
  "@typescript-eslint/no-array-constructor": ["error"],
  "@typescript-eslint/no-empty-function": ["error"],
  "@typescript-eslint/no-empty-interface": ["error"],
  "@typescript-eslint/no-explicit-any": ["warn"],
  "@typescript-eslint/no-inferrable-types": ["error"],
  "@typescript-eslint/no-misused-new": ["error"],
  "@typescript-eslint/no-namespace": ["error"],
  "@typescript-eslint/no-non-null-assertion": ["warn"],
  "@typescript-eslint/no-this-alias": ["error"],
  "@typescript-eslint/no-unused-vars": ["warn"],
  "@typescript-eslint/no-use-before-define": ["error"],
  "@typescript-eslint/no-var-requires": ["error"],
  "@typescript-eslint/prefer-namespace-keyword": ["error"],
  "@typescript-eslint/triple-slash-reference": ["error"],
  "@typescript-eslint/type-annotation-spacing": ["error"]
};
