name: Publish prerelease to NPM registry

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the job on'
        required: true

jobs:
  build:
    if: ${{ github.event.inputs.branch != 'main' }}
    runs-on: ubuntu-latest
    env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: yarn install --frozen-lockfile
    - run: yarn semantic-release --branches ${{ github.event.inputs.branch }}
