name: Manual Publish to NPM registry

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: yarn install --frozen-lockfile
    - run: yarn semantic-release
