name: Publish to NPM registry

on:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest

    env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: yarn install --frozen-lockfile
    - run: yarn semantic-release
