name: "Semantic Pull Request"

on: [pull_request]

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
